//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDiagnoses
    {
        public int DiagnosisRecordId { get; set; }
        public int CardId { get; set; }
        public int StaffId { get; set; }
        public int DiagnosisId { get; set; }
        public Nullable<System.DateTime> OpenedAt { get; set; }
        public Nullable<System.DateTime> ClosedAt { get; set; }
        public int IsClosed { get; set; }
        public string DoctorNote { get; set; }
    
        public virtual MedicalCards MedicalCards { get; set; }
        public virtual Diagnoses Diagnoses { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
