//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTests
    {
        public int TestId { get; set; }
        public int CardId { get; set; }
        public int StaffId { get; set; }
        public string TestName { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<System.DateTime> RecordedAt { get; set; }
    
        public virtual MedicalCards MedicalCards { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
