//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalCards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalCards()
        {
            this.CardDiagnoses = new HashSet<CardDiagnoses>();
            this.LabTests = new HashSet<LabTests>();
            this.Referrals = new HashSet<Referrals>();
        }
    
        public int CardId { get; set; }
        public int PatientId { get; set; }
        public Nullable<System.DateTime> OpenedAt { get; set; }
        public Nullable<System.DateTime> ClosedAt { get; set; }
        public int IsClosed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardDiagnoses> CardDiagnoses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabTests> LabTests { get; set; }
        public virtual Patients Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referrals> Referrals { get; set; }
    }
}
