//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescriptions
    {
        public int PrescriptionId { get; set; }
        public int PatientId { get; set; }
        public int MedicationId { get; set; }
        public int StaffId { get; set; }
        public string Instructions { get; set; }
        public Nullable<System.DateTime> IssuedAt { get; set; }
        public string Status { get; set; }
    }
}
