//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referrals
    {
        public int ReferralId { get; set; }
        public int CardId { get; set; }
        public int StaffId { get; set; }
        public int DepartmentId { get; set; }
        public string Purpose { get; set; }
        public Nullable<System.DateTime> IssuedAt { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual MedicalCards MedicalCards { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
